dbt_dsg_app:
  outputs:
    dev:
      account: bcb55215.us-east-1
      database: DEV_DB
      password: Snowflake1
      role: ACCOUNTADMIN
      schema: CONTACT_COMPANY
      threads: 4
      type: snowflake
      user: DEV_AIRFLOW
      warehouse: ldf_transform
  target: dev