dbt_dsg_app:
  outputs:
    dev:
      account: bcb55215.us-east-1
      database: DEV_QA
      password: Snowflake1
      role: ACCOUNTADMIN
      schema: DBT_POC
      threads: 4
      type: snowflake
      user: DEV_AIRFLOW
      warehouse: dev_transform
  target: dev